# Generated by Django 5.0.2 on 2024-02-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='source',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='question',
            field=models.TextField(),
        ),
    ]
